// File: Alien.h
// Date: 10/14/2024 - 10/17/2024
// Description: Header file for linked list (Alienlist) and nodes (Alien)
#ifndef ALIEN_H
#define ALIEN_H
#include <iostream>
using namespace std;

/********** DO NOT EDIT THIS FILE **********/
/********** DO NOT EDIT THIS FILE **********/
/********** DO NOT EDIT THIS FILE **********/


// Alien (node) struct used for the Alienlist class
struct Alien{
  // Default Alien class constructor
  Alien(){
    m_name = "Alien";
    m_next = nullptr;
  }
  // Overloaded Alien class constructor
  Alien(string name){
    m_name = name;
    m_next = nullptr;
  }  
  string m_name;   // Name of the alien
  Alien* m_next;   // Pointer to next node
};


// Alienlist (linked list) class
class AlienList{
public:
  AlienList();                    // Default AlienList class constructor
  ~AlienList();                   // AlienList class destructor
  void Display();                 // Displays all data and list of aliens
  void RemoveAlien(string name);  // Removes alien with given name
  void Insert(const string name); // Adds alien to end of the list
  void RemoveHead();              // Removes head of the list
private:
  Alien* m_head;                  // Track head of list
  Alien* m_tail;                  // Track tail of list
  unsigned int m_size;            // Number of aliens in list
};

#endif
