// File: lab7.cpp
// Date: 10/14/2024 - 10/17/2024
// Description: Driver for the lab. 

#include "Alien.h"
#include <iostream>
using namespace std;

/********** DO NOT EDIT THIS FILE **********/
/********** DO NOT EDIT THIS FILE **********/
/********** DO NOT EDIT THIS FILE **********/


int main(){
  cout << "Booting up the Black Mesa Research Facility Xen Database!\n";
  AlienList xenDatabase; // Create linked list
  
  // Inserting aliens (nodes) to the list
  xenDatabase.Insert("Headcrab");
  xenDatabase.Insert("Bullsquid");
  xenDatabase.Insert("Houndeye");
  xenDatabase.Insert("Barnicle");
  xenDatabase.Insert("Vortigaunt");
  xenDatabase.Insert("Antlion");
  xenDatabase.Insert("Pit Drone");
  xenDatabase.Insert("Tentacle");
  xenDatabase.Insert("Ichthyosaur");
  xenDatabase.Insert("Gargantua");
  /* Fun fact: One of these creatures is not like the other... */
  
  // Displays the list if properly implemented
  cout << "Displaying database...\n";
  xenDatabase.Display();
  
  // Remove alien (node) tests
  cout << "*****************************************************\n";
  cout << "Error!!! The Black Mesa database is experiencing\n";
  cout << "technical difficulties due to extreme energy hazard\n";
  cout << "in sector C.\n";
  cout << "*****************************************************\n";
  xenDatabase.RemoveAlien("Bullsquid"); // Remove middle
  xenDatabase.RemoveAlien("Vortigaunt");// Remove middle
  xenDatabase.RemoveAlien("Headcrab");  // Remove head
  xenDatabase.RemoveAlien("Gonome");    // Error case 
  xenDatabase.RemoveAlien("Gargantua"); // Remove tail
  xenDatabase.RemoveAlien("Houndeye");  // Remove middle
  
  cout << "Displaying database...\n";
  xenDatabase.Display();
  
  // Adding some more nodes
  cout << "New entries detected!\n";
  xenDatabase.Insert("Gonarch");
  xenDatabase.Insert("Nihilanth");
  
  cout << "Displaying database...\n";
  xenDatabase.Display();
  
  cout << "*****************************************************\n";
  cout << "ATTENTION!!! The Black Mesa database is experiencing\n";
  cout << "technical difficulties due to extreme energy hazard\n";
  cout << "in sector C again... shutting down to preserve data!\n";
  cout << "*****************************************************\n";
  
  return 0;
}
